databases:
  - name: beaver2_DB
    databaseName: beaver2_db
    user: beaver2
    region: singapore

services:
  - type: web
    name: beaver2
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: beaver2_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

